name: registry
version: 0.1.0.5
synopsis: data structure for assembling "components"

description: This library provides a "Registry" which is a data structure containing
             a list of functions and values representing dependencies in a
             directed acyclic graph.
             A `make` function can then be used to create a value of a specific
             type out of the registry.

             You can start with the [README](https://github.com/etorreborre/registry/blob/master/README.md)
             for a full description of the library.

category: Control

license: MIT
license-file: LICENSE.txt

maintainer: etorreborre@yahoo.com
git: https://github.com/etorreborre/registry

ghc-options:
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -fhide-source-paths
  -fprint-potential-instances
  -optP-Wno-nonportable-include-path

default-extensions:
 - BangPatterns
 - DefaultSignatures
 - EmptyCase
 - ExistentialQuantification
 - FlexibleContexts
 - FlexibleInstances
 - FunctionalDependencies
 - GADTs
 - GeneralizedNewtypeDeriving
 - InstanceSigs
 - KindSignatures
 - LambdaCase
 - MultiParamTypeClasses
 - MultiWayIf
 - NamedFieldPuns
 - NoImplicitPrelude
 - OverloadedStrings
 - PatternSynonyms
 - Rank2Types
 - RankNTypes
 - ScopedTypeVariables
 - StandaloneDeriving
 - TupleSections
 - TypeApplications
 - TypeFamilies
 - TypeFamilyDependencies
 - TypeOperators

dependencies:
  - base       >= 4.7 && < 5
  - exceptions           < 0.11
  - protolude            < 0.3
  - resourcet            < 1.3
  - text                 < 2
  - transformers-base    < 0.5

library:
  source-dirs: src

  ghc-options:
    -Wincomplete-uni-patterns

tests:
  spec:
    main: test.hs
    source-dirs:
      - test
    dependencies:
      - registry
      - async            < 2.3
      - hedgehog         < 0.7
      - hedgehog-corpus  < 0.2
      - io-memoize       < 1.2
      - MonadRandom      < 0.6
      - random           < 2.0
      - tasty            < 1.2
      - tasty-discover   < 4.3
      - tasty-hedgehog   < 0.3
      - tasty-th         < 0.2
      - text             < 2

    ghc-options:
      -threaded
      -rtsopts
      -with-rtsopts=-N
      -fno-warn-orphans
      -fno-warn-missing-signatures
      -optP-Wno-nonportable-include-path
